// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"true","Custom Image":"CarmineOakGilokko","Fade Out Time":"60","Fade In Time":"60","Wait Time":"120"}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"WAY_Core","status":true,"description":"v2.0.0 WAY Core Utility Plugin. Place it above all WAY plugins. <WAY_Core>","parameters":{}},
{"name":"WAY_EvalText","status":true,"description":"v2.3.0 Use JavaScript Code in textboxes. <WAY_EvalText>","parameters":{}}
];
